name: "setup-autopkg"
description: "Sets up autopkg"
inputs:
  name:
    required: false
    description: "Name"

runs:
  using: "composite"
  steps:
    - name: checkout autopkg master
      uses: actions/checkout@v3
      with:
        repository: autopkg/autopkg
        path: autopkg
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        # following should be any requirements files used later:
        cache-dependency-path: |
          autopkg/gh_actions_requirements.txt

    - name: Install AutoPkg Reqirements
      run: pip install --requirement autopkg/gh_actions_requirements.txt
      shell: bash

    - name: create empty config windows
      # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if not exist "%USERPROFILE%/AppData/Local/Autopkg" mkdir "%USERPROFILE%/AppData/Local/Autopkg"
        if not exist "%USERPROFILE%/AppData/Local/Autopkg/config.json" echo {} > "%USERPROFILE%/AppData/Local/Autopkg/config.json"

    - name: create default autopkg config file Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        cd ~ && mkdir -p .config/Autopkg
        cd ~ && echo {} > .config/Autopkg/config.json
