---
name: Test AutoPkg Release Brew

on:
  push:
    paths:
      - ".github/workflows/AutoPkgReleaseBrew.yaml"
      - "AutoPkgRecipe/autopkg.rb.mustache"
      - "AutoPkgRecipe/AutoPkgRelease.brew.recipe.yaml"
      - "AutoPkgRecipe/AutoPkgReleasePkg.download.recipe.yaml"
  pull_request:
    paths:
      - ".github/workflows/AutoPkgReleaseBrew.yaml"
      - "AutoPkgRecipe/autopkg.rb.mustache"
      - "AutoPkgRecipe/AutoPkgRelease.brew.recipe.yaml"
      - "AutoPkgRecipe/AutoPkgReleasePkg.download.recipe.yaml"

jobs:
  AutoPkgBrew:
    runs-on: macos-latest
    steps:
      - name: Set github token autopkg
        # required for githubreleaseinfoprovider in github actions
        # without this, API limits will be hit
        run: |
          cd ~
          echo ${{ secrets.GITHUB_TOKEN }} > ".autopkg_gh_token"
      - name: Set github token homebrew
        # echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> /Users/runner/.bash_profile
        run: |
          cd ~
          echo 'export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> .bash_profile
          pwd

      - uses: actions/checkout@v6

      - name: Read Python version
        id: pyver
        shell: bash
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: setup-autopkg
        uses: ./.github/actions/setup-autopkg
        with:
          use-python-version: ${{ steps.pyver.outputs.version }}

      - name: Install requirements
        run: pip install --requirement requirements.txt

      - name: run test recipe autopkg
        run: python autopkg/Code/autopkg run -v Test-Recipes/AutopkgCore.test.recipe.yaml

      - name: run brew recipe
        # See the following files used:
        # - https://github.com/jgstew/jgstew-recipes/blob/main/AutoPkgRecipe/autopkg.rb.mustache
        # - https://github.com/jgstew/jgstew-recipes/blob/main/AutoPkgRecipe/AutoPkgReleasePkg.download.recipe.yaml
        # - https://github.com/jgstew/jgstew-recipes/blob/main/AutoPkgRecipe/AutoPkgRelease.brew.recipe.yaml
        run: python autopkg/Code/autopkg run -vv AutoPkgRecipe/AutoPkgRelease.brew.recipe.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create local brew tap
        run: |
          brew tap-new jgstew/jgstew-recipes
          mkdir -p "$(brew --prefix)/Library/Taps/jgstew/homebrew-jgstew-recipes/Casks"

      - name: setup cask to test
        run: |
          cp /Users/runner/Library/AutoPkg/Cache/com.github.jgstew.brew.AutoPkgRelease/autopkg.rb "$(brew --prefix)/Library/Taps/jgstew/homebrew-jgstew-recipes/Casks/autopkg.rb"

      - name: run brew fetch
        run: brew fetch --cask --verbose jgstew/jgstew-recipes/autopkg
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run brew install
        run: brew install --cask --verbose jgstew/jgstew-recipes/autopkg
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test brew installed autopkg
        run: autopkg run -v Test-Recipes/AutopkgCore.test.recipe.yaml

      - name: run brew audit
        run: brew audit --cask --verbose --strict jgstew/jgstew-recipes/autopkg
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run brew style
        run: brew style --cask jgstew/jgstew-recipes/autopkg
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
