---
name: Test AutoPkg Core Processors

on:
  push:
    paths:
      - "Test-Recipes/AutopkgCore.test.recipe.yaml"
      - ".github/workflows/AutoPkgCoreProcessors.yaml"
      - ".github/actions/setup-autopkg/action.yaml"
  pull_request:
    paths:
      - "Test-Recipes/AutopkgCore.test.recipe.yaml"
      - ".github/workflows/AutoPkgCoreProcessors.yaml"
      - ".github/actions/setup-autopkg/action.yaml"

jobs:
  AutoPkgCoreTest:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set github token autopkg
        # required for githubreleaseinfoprovider in github actions
        # without this, API limits will be hit
        run: |
          cd ~
          echo ${{ secrets.GITHUB_TOKEN }} > ".autopkg_gh_token"

      - name: checkout this repo
        uses: actions/checkout@v4

      - name: setup-autopkg local action
        uses: ./.github/actions/setup-autopkg

      - name: Install requirements
        run: pip install --requirement requirements.txt

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/AutopkgCore.test.recipe.yaml

      - name: create file
        shell: bash
        run: |
          cat <<'EOFEOF' > AutopkgCore.test.recipe.yaml
          ---
          Description: Test AutoPkg Core Cross Platform Processors
          Identifier: com.github.autopkg.test.AutoPkgCore
          Input:
            NAME: AutoPkgCoreTest
          MinimumVersion: "2.3"
          Process:
            # TODO: add: PlistEditor, PlistReader, Unarchiver, Versioner
            - Processor: DeprecationWarning
              # https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/DeprecationWarning.py
              Arguments:
                warning_message: "This is just a test, not a real Deprecation Warning. Created File"
            - Processor: GitHubReleasesInfoProvider
              Arguments:
                github_repo: audacity/audacity
                asset_regex: .*64bit\.exe$
                include_prereleases: False
          EOFEOF
      - name: get file contents
        shell: bash
        run: cat AutopkgCore.test.recipe.yaml
      - name: run integration recipe created in action
        run: python autopkg/Code/autopkg run -vvvvvv AutopkgCore.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/autopkg.yaml
