# Your .github/workflows/coverity.yml file.
name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/coverity.yaml"

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vapier/coverity-scan-action@v1.6.0
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          build_language: "other"
          project: "jgstew-recipes"
