---
name: Test Processor URLDownloaderPython

on:
  push:
    paths:
      - "SharedProcessors/URLDownloaderPython.py"
      - "Test-Recipes/URLDownloaderPython.test.recipe.yaml"
      - ".github/workflows/Processor_URLDownloaderPython.yaml"
  pull_request:
    paths:
      - "SharedProcessors/URLDownloaderPython.py"
      - "Test-Recipes/URLDownloaderPython.test.recipe.yaml"
      - ".github/workflows/Processor_URLDownloaderPython.yaml"

jobs:
  ProcessorURLDownloaderPython:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: setup-autopkg local action
        uses: ./.github/actions/setup-autopkg

      - name: Install requirements
        run: pip install --requirement requirements.txt

      # update ssl certs:
      - name: Install/Update Python certs
        run: pip install --upgrade certifi

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/URLDownloaderPython.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/AutoPkgCoreProcessors.yaml
