---
name: Test Processor Loading

on:
  push:
    paths:
      - "SharedProcessors/**"
      - "test_processors_load.sh"
      - "requirements.txt"
      - ".github/workflows/Processors_Test_Loading.yaml"
  pull_request:
    paths:
      - "SharedProcessors/**"
      - "test_processors_load.sh"
      - "requirements.txt"
      - ".github/workflows/Processors_Test_Loading.yaml"

jobs:
  test-processor-loading:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prereq macOS
        if: runner.os == 'macOS'
        run: |
          brew install libmagic cairo libffi pkg-config
          echo "DYLD_LIBRARY_PATH=$(brew --prefix)/lib" >> "${GITHUB_ENV}"

      - name: Install prereq Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          & "C:\msys64\usr\bin\pacman.exe" -S --noconfirm mingw-w64-x86_64-cairo
          Add-Content $env:GITHUB_PATH "C:\msys64\mingw64\bin"

      - name: setup-autopkg
        uses: ./.github/actions/setup-autopkg
        with:
          use-python-version: "3.11"

      - name: Install requirements
        run: pip install --requirement requirements.txt

      - name: Install linux python prereq
        if: runner.os == 'Linux'
        run: |
          pip uninstall oscrypto -y
          pip install git+https://github.com/wbond/oscrypto.git@d5f3437

      - name: Run processor loading tests
        run: bash test_processors_load.sh
        shell: bash
