---
name: Test Processor FileMsiGetProperty

on:
  push:
    paths:
      - "SharedProcessors/FileMsiGetProperty.py"
      - "Test-Recipes/FileMsiGetProperty.test.recipe.yaml"
      - ".github/workflows/Processor_FileMsiGetProperty.yaml"
  pull_request:
    paths:
      - "SharedProcessors/FileMsiGetProperty.py"
      - "Test-Recipes/FileMsiGetProperty.test.recipe.yaml"
      - ".github/workflows/Processor_FileMsiGetProperty.yaml"

jobs:
  ProcessorFileMsiGetProperty:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # only needed on self hosted windows runners:
      - name: set powershell execution policy CurrentUser
        if: runner.os == 'Windows'
        shell: cmd
        run: powershell -command "Set-ExecutionPolicy -Force -ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: Install requirements
      #   run: pip install --requirement requirements.txt

      - name: checkout autopkg dev
        uses: actions/checkout@v3
        with:
          repository: autopkg/autopkg
          path: autopkg
          ref: dev

      - name: Set github token autopkg
        # required for githubreleaseinfoprovider in github actions
        # without this, API limits will be hit
        run: |
          cd ~
          echo ${{ secrets.GITHUB_TOKEN }} > ".autopkg_gh_token"

      - name: Install AutoPkg Reqirements
        run: pip install --requirement autopkg/gh_actions_requirements.txt
      - name: create empty config windows
        # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          if not exist "%USERPROFILE%/AppData/Local/Autopkg" mkdir "%USERPROFILE%/AppData/Local/Autopkg"
          if not exist "%USERPROFILE%/AppData/Local/Autopkg/config.json" echo {} > "%USERPROFILE%/AppData/Local/Autopkg/config.json"
      - name: create default autopkg config file Linux
        if: runner.os == 'Linux'
        run: |
          cd ~ && mkdir -p .config/Autopkg
          cd ~ && echo {} > .config/Autopkg/config.json
      - name: install msiinfo linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install msitools -y
      - name: install msiinfo MacOS
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install msitools
      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/FileMsiGetProperty.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/AutoPkgCoreProcessors.yaml
