---
name: Test Processor DateTimeFromString

on:
  push:
    paths:
      - "SharedProcessors/DateTimeFromString.py"
      - "Test-Recipes/DateTimeFromString.test.recipe.yaml"
      - ".github/workflows/Processor_DateTimeFromString.yaml"
  pull_request:
    paths:
      - "SharedProcessors/DateTimeFromString.py"
      - "Test-Recipes/DateTimeFromString.test.recipe.yaml"
      - ".github/workflows/Processor_DateTimeFromString.yaml"

jobs:
  ProcessorDateTimeFromString:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout this repo
        uses: actions/checkout@v6

      - name: install ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libxml2-dev libxslt1-dev zlib1g-dev build-essential

      - name: install macos dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install libxml2 libxslt

      - name: Read Python version
        id: pyver
        shell: bash
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: setup-autopkg local action
        uses: ./.github/actions/setup-autopkg
        with:
          use-python-version: ${{ steps.pyver.outputs.version }}

      # the processors being tested don't need these:
      # - name: Install requirements
      #   run: pip install --requirement requirements.txt

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/DateTimeFromString.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/AutoPkgCoreProcessors.yaml
