---
name: Test Processor URLDownloaderPython

on:
  push:
    paths:
      - "SharedProcessors/URLDownloaderPython.py"
      - "Test-Recipes/URLDownloaderPython.test.recipe.yaml"
      - ".github/workflows/Processor_URLDownloaderPython.yaml"
  pull_request:
    paths:
      - "SharedProcessors/URLDownloaderPython.py"
      - "Test-Recipes/URLDownloaderPython.test.recipe.yaml"
      - ".github/workflows/Processor_URLDownloaderPython.yaml"

jobs:
  ProcessorURLDownloaderPython:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # only needed on self hosted windows runners:
      - name: set powershell execution policy CurrentUser
        if: runner.os == 'Windows'
        shell: cmd
        run: powershell -command "Set-ExecutionPolicy -Force -ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: git clone autopkg, checkout dev
        run: |
          git clone https://github.com/autopkg/autopkg.git
          cd autopkg
          git checkout dev
      - name: Install AutoPkg Reqirements
        run: pip install --requirement autopkg/new_requirements.txt
      - name: Install requirements
        run: pip install --requirement requirements.txt
      - name: create empty config windows
        # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          if not exist "%USERPROFILE%/AppData/Local/Autopkg" mkdir "%USERPROFILE%/AppData/Local/Autopkg"
          if not exist "%USERPROFILE%/AppData/Local/Autopkg/config.json" echo {} > "%USERPROFILE%/AppData/Local/Autopkg/config.json"
      - name: create default autopkg config file Linux
        if: runner.os == 'Linux'
        run: |
          cd ~ && mkdir -p .config/Autopkg
          cd ~ && echo {} > .config/Autopkg/config.json
      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/URLDownloaderPython.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/AutoPkgCoreProcessors.yaml
