---
name: Test Processor FileMsiGetProperty

on:
  push:
    paths:
      - "SharedProcessors/FileMsiGetProperty.py"
      - "Test-Recipes/FileMsiGetProperty.test.recipe.yaml"
      - ".github/workflows/Processor_FileMsiGetProperty.yaml"
  pull_request:
    paths:
      - "SharedProcessors/FileMsiGetProperty.py"
      - "Test-Recipes/FileMsiGetProperty.test.recipe.yaml"
      - ".github/workflows/Processor_FileMsiGetProperty.yaml"

jobs:
  ProcessorFileMsiGetProperty:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: setup-autopkg local action
        uses: ./.github/actions/setup-autopkg

      - name: Set github token autopkg
        # required for githubreleaseinfoprovider in github actions
        # without this, API limits will be hit
        run: |
          cd ~
          echo ${{ secrets.GITHUB_TOKEN }} > ".autopkg_gh_token"

      - name: install msiinfo linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install msitools -y

      - name: install msiinfo MacOS
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install msitools

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/FileMsiGetProperty.test.recipe.yaml
# Related:
# - https://github.com/jgstew/bigfix-content/blob/master/.github/workflows/AutoPkgCoreProcessors.yaml
