---
name: Test Processor Loading

on:
  push:
    paths:
      - "SharedProcessors/**"
      - "test_processors_load.sh"
      - "requirements.txt"
      - ".github/workflows/Processors_Test_Loading.yaml"
  pull_request:
    paths:
      - "SharedProcessors/**"
      - "test_processors_load.sh"
      - "requirements.txt"
      - ".github/workflows/Processors_Test_Loading.yaml"

jobs:
  test-processor-loading:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install prereq macOS
        if: runner.os == 'macOS'
        run: brew install libmagic cairo libffi pkg-config

    #   - name: Install prereq Windows
    #     if: runner.os == 'Windows'
    #     run: choco install -y speech-dispatcher cairo libmagic jq p7zip curl git wget sevenzip libffi

      - name: setup-autopkg
        uses: ./.github/actions/setup-autopkg
        with:
          use-python-version: "3.11"

      - name: Install requirements
        run: pip install --requirement requirements.txt

      - name: Install linux python prereq
        if: runner.os == 'Linux'
        run: |
          pip uninstall oscrypto -y
          pip install git+https://github.com/wbond/oscrypto.git@d5f3437

    #   - name: Create venv
    #     run: python -m venv .venv
    #     shell: bash

    #   - name: Install requirements (Unix)
    #     if: runner.os != 'Windows'
    #     run: .venv/bin/pip install --requirement requirements.txt

    #   - name: Install requirements (Windows)
    #     if: runner.os == 'Windows'
    #     run: .venv/Scripts/pip install --requirement requirements.txt

      - name: Run processor loading tests
        run: bash test_processors_load.sh
        shell: bash
