---
name: Test setup-autopkg-actions

on:
  push:
    paths:
      - ".github/workflows/Test_setup-autopkg-actions.yaml"
  pull_request:
    paths:
      - ".github/workflows/Test_setup-autopkg-actions.yaml"

jobs:
  Test_setup-autopkg-actions:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test Action setup-autopkg
    steps:
      - uses: actions/checkout@v4

      - name: test setup-autopkg-actions action
        # https://github.com/orgs/community/discussions/26073
        uses: autopkg/setup-autopkg-actions@v0.1.2

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/AutopkgCore.test.recipe.yaml
